version: '3.3'

services:
   db:
     image: mysql:5.7
     volumes:
       - db_data:/var/lib/mysql
     restart: always
     environment:
       MYSQL_ROOT_PASSWORD_FILE: /run/secrets/MYSQL_PASSWORD
       MYSQL_DATABASE: wordpress
       MYSQL_USER: wordpress
       MYSQL_PASSWORD_FILE: /run/secrets/MYSQL_PASSWORD
      secret:
        source: MYSQL_PASSWORD
        target: MYSQL_PASSWORD

   wordpress:
     depends_on:
       - db
     image: wordpress:latest
     ports:
       - "8000:80"
     restart: always
     environment:
       WORDPRESS_DB_HOST: db:3306
       WORDPRESS_DB_USER: wordpress
       WORDPRESS_DB_PASSWORD_FILE: /run/secrets/MYSQL_PASSWORD
       WORDPRESS_DB_NAME: wordpress
      secret:
        source: MYSQL_PASSWORD
        target: MYSQL_PASSWORD
        mode: 0400

volumes:
    db_data: {}

secrets:
  MYSQL_PASSWORD:
    external: true
